[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[profile.version] 
solc_version = "0.8.20"




# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options


#solc_version: https://binaries.soliditylang.org/bin/soljson-v0.8.20+commit.a1b79de6.js
